### ISSUE TITLE
能适配下iPhone X 吗

### ISSUE THREAD

**Issue by IsLandSea** [AnnaMa1992/NormalHeaderAngPageView#8]

**Comment by xiaofeiMa** [comment]
初始化 mainTableView frame 的时候 y坐标设置为x的导航栏高度就可以，如果你觉得底部遮挡到x的按钮一般会设置tableview 和collectionView 的contentInset 为self.tableView.contentInset = UIEdgeInsetsMake(0, 0,34, 0);
